### ISSUE TITLE
data-dir

### ISSUE THREAD

**Issue by duog** [sol/hpack#100]
Hpack does not seem to support the data-dir cabal option. Is there a reason for this? If not I would be happy to contribute a fix.

**Comment by mitchellwrosen** [comment]
@duog No reason. Still interested?

**Comment by duog** [comment]
I am, will try to get you something this week.

**Comment by sol** [comment]
I never wanted to use `data-dir` myself, as `data-files` was always good enough.

Anybody who wants to use this, please feel free to open a PR.
