### ISSUE TITLE
data files are excluded if they do not exist

### ISSUE THREAD

**Issue by duog** [sol/hpack#101]
I have been using template haskell to create configuration files, and including those files in the data-files of a cabal package.

Hpack seems to check whether files exist before including them in the generated cabal file, which means I have to create stub files to get Hpack to work. This is annoying because I have to commit this stub to source control, and be sure to not commit generated files.

In the case where glob patterns are not used, I think the fix is as simple as not excluding a non-existant data file from the generated .cabal file.

I would like to be able to generate files of arbitrary name in template haskell, and have a glob pattern in the package.yaml file pick up each of those generated files, but I suspect this is impractical.

**Comment by simonmichael** [comment]
I just ran into this due an over-zealous clean script, and it caused some head-scratching. I think it would be better not to check for file existence here.

**Comment by sol** [comment]
Sorry guys for the late reply.  This is due to glob expansion.  A fix may be somewhat fragile, that's why I was not excited to work on it so far.

I agree that in the case where no globs are used, `hpack` should not discard files if they don't exist.  So I'm labeling this as a bug.

**Comment by sol** [comment]
Blocked by https://github.com/Deewiant/glob/issues/10.

**Comment by sol** [comment]
Now that Deewiant/glob#10 is resolved we are in a better position to change what `hpack` does.  So what exact behavior do we want?

- If a file pattern is a literal file name, we want to keep it regardless of whether that file exists or not.  Do we want a warning if the file does not exist?

- If a file pattern is not a literal file name (contains wildcards), we expand it.  If it does not match anything it's effectively discarded; currently we emit a warning if that happens.  Do we want to keep that warning?

By default, the change would affect:
 - `data-files`
  - `extra-source-files`
 - `c-sources`
 - `js-sources`

**Comment by sol** [comment]
@simonmichael @duog Are you still interested in this?  If not, I'll close this issue.

**Comment by duog** [comment]
I am still interested in this though I don't currently have the time to commit to do it.
I think that we certainly do want a warning if a literal file does not exist.
I would think that a warning for a non-literal filename with no matches would be appropriate, but I can see cases where it would be superfluous.
I don't see any reason one wouldn't want this behaviour in all the sections you list.

**Comment by sol** [comment]
@duog Thanks!  We now keep literal files, even if non-existing and warn.
