### ISSUE TITLE
c-sources marked as "unknown field" when hpack is built with aeson-0.9 in Stack

### ISSUE THREAD

**Issue by lukexi** [sol/hpack#102]
I haven't had a chance to get all the way to the root of this yet, but I'm logging this here so I don't forget it.

The copy of hpack that's built into stack exhibits a bug that doesn't occur with a vanilla hpack installation, namely displaying: 
```
WARNING: Ignoring unknown field "c-sources" in library section
```
when building a library with a c-sources field.

I traced the difference to hpack defining 
```
extra-deps:
- aeson-0.11.0.0
```
in its `stack.yaml`, which is not defined in Stack's `stack.yaml`. When I add that to Stack's `stack.yaml` the problem disappears.

/cc @mgsloan

**Comment by mgsloan** [comment]
Addressed in https://github.com/commercialhaskell/stack/commit/d8e5c54e7ae1e5aa08bc663d789115826d5a5645 , and opened a hpack PR with bumped aeson bound.

**Comment by lukexi** [comment]
Awesome, thanks Michael!!

**Comment by sol** [comment]
I think this is already addressed, closing.
