### ISSUE TITLE
Split ghc-options on multiple lines in the cabal file

### ISSUE THREAD

**Issue by harendra-kumar** [sol/hpack#105]
The `ghc-options` line in cabal becomes too long if there are many options specified. It will help readability if the line is split into multiple lines whenever it gets longer than 80 chars.

**Comment by mitchellwrosen** [comment]
This feature's already in. @sol this can be closed

**Comment by sol** [comment]
I don't think this is implemented.  But I don't really consider it crucial, as the cabal file is generated output that I don't care that much about.

@harendra-kumar if you still care about this, feel free to send a PR.

Closing.
