### ISSUE TITLE
Require package name?

### ISSUE THREAD

**Issue by mgsloan** [sol/hpack#109]
While it is clever to infer the package name from the directory, it causes issues when hpack files are present in hackage tarballs: https://github.com/commercialhaskell/stack/issues/2254

I haven't tested, but I believe this will even be an issue when you do `stack unpack` on the package, as the unpacked dir defaults to having the package name as well as the package version.

**Comment by sol** [comment]
Hey, inferring the package name is controversial. It's convenient when you don't really care about the package name and want something working with as little overhead as possible. But literally in almost all other cases you want to specify it.

So if there is strong demand to require it and a PR I'll probably merge.

**Comment by sol** [comment]
But we may want to make it a warning first.

**Comment by sol** [comment]
In the specific case of commercialhaskell/stack#2254, what about putting the downloaded dependency into `.stack-work/downloaded/Po3M4t2NzhXM/reserve` instead of `.stack-work/downloaded/Po3M4t2NzhXM`.

**Comment by mgsloan** [comment]
I think it makes sense to clone packages to a better dir like that - opened https://github.com/commercialhaskell/stack/issues/2261

**Comment by sol** [comment]
Yes, I think I like that.
