### ISSUE TITLE
 provide a command line option to specify output file

### ISSUE THREAD

**Issue by k0001** [sol/hpack#113]
Complementing #106 

My use case for this is that when running `hpack` from a script, it would be best to call it as:

```
hpack -i input.yaml -o output.cabal
```

Instead of having to `cd` to the directory where the `input.yaml` file is located, and having to “guess” the name of the output cabal file.

**Comment by mitchellwrosen** [comment]
I can do this but there is not currently a command-line parser dependency in hpack. @sol is it appropriate to add one to get this feature in? If so, which?

- optparse-applicative
- optparse-generic
- something else?

**Comment by sol** [comment]
Regarding command-line parser, `optparse-*` does not follow GNU getopt conventions.  For that reason I'm in favor of using `System.Console.GetOpt` if we ever have the need for a full-blown command-line parser.

**Comment by sol** [comment]
@k0001 I implemented #106.  But regarding this request I'm still puzzled what exactly the use case is.  Do you want to specify an output directory or the output file name?  I'm asking because I think the cabal file name should always match the package name.

**Comment by sol** [comment]
@k0001 You can now dump the generated cabal file to `stdout` by passing `-` on the command line, e.g. `hpack package.yaml -`.  This will not behave as vanilla `hpack` and is only meant for debugging.

Closing.
