### ISSUE TITLE
Problems when a directory field contains a dot

### ISSUE THREAD

**Issue by yamadapc** [sol/hpack#119]
When a field that takes a directory contains a dot, hpack's renderer will generate a line with nothing but a `.` in it. However, this is invalid in a cabal file, as dots on their single lines are meant to express empty-lines (I think, I can't find the documentation [the source that does it is here](https://github.com/haskell/cabal/blob/9b4712583ca390d0f034cc66eca4de51c00cc8d0/Cabal/Distribution/ParseUtils.hs#L576)).

A simple example of the bug is here: https://gist.github.com/0cc7f8f8e2cbc9ee7bbf82876a822e28

In there, `source-dirs: .` generates an invalid cabal file. Though this specific case isn't super common, without specifying `source-dirs: .`, `hpack` won't include the `other-modules` section for the modules in the current directory (I'd consider that another ticket).

- - -

My idea for a fix would be to output:
```
field: .
  , other-value
  , other-value
```

Whenever `.` is a value.

**Comment by soenkehahn** [comment]
Another solution might be to replace `.` with `./.`.

**Comment by yamadapc** [comment]
Mm... Yeah, that could be a much cleaner solution.
