### ISSUE TITLE
hpack collpases newlines in the description field

### ISSUE THREAD

**Issue by harendra-kumar** [sol/hpack#130]
Something like this in hpack.yaml description field:
```
a
.
b
```

Gets collapsed to this in .cabal:
```a . b```

So everything becomes a single line. Is there something that I am missing or that's how it works?

**Comment by sol** [comment]
Read up on yaml syntax ;)

**Comment by sol** [comment]
closing this

**Comment by harendra-kumar** [comment]
@sol Alright, on a quick read it seems we can use '\n' as an escape, or a block indicator '|' or '|-' to insert blocks with newlines. Will it be a good idea to add a short note in the description field help? 

Also, I looked at the hpack examples at the beginning of the readme and none of them had a description field which was preserving newlines. We should add an example which shows this. It will help others facing the same problem. We cannot assume everyone to be an expert in YAML.

**Comment by sol** [comment]
Pull request please
