### ISSUE TITLE
Make the link between package.yaml files and hpack more clear

### ISSUE THREAD

**Issue by sjakobi** [sol/hpack#138]
This issue is motivated by [this SO question](http://stackoverflow.com/questions/40332040/what-goes-in-a-stack-package-yaml-file). Basically, users who come across a package.yaml file have a hard time making the link to hpack. E.g. if I google "haskell package.yaml", the only result on the first page that points at hpack is the above SO question.

I have two alternative ideas on how to fix this:

* Rename `package.yaml` to `hpack.yaml`: The new name is much more googleable.

* Let hpack insert a comment on the first line of each `package.yaml` file with a text like

  ```yaml
  # This file describes a Haskell package in the hpack format.
  # See https://github.com/sol/hpack#readme for more info.
  ```

**Comment by mitchellwrosen** [comment]
+1 to `hpack.yaml`

**Comment by sol** [comment]
Modifying `package.yaml` is not a option for me.  I myself would certainly be annoyed by `hpack` doing this.

I'm also not in favor or renaming `package.yaml` to `hpack.yaml` for two reasons. One of them is practical:

 - Renaming comes at a non-zero cost

The other one is personal:

 - I like `package.yaml`

Regarding googleability, the [generic Google results for `haskell package.yaml`](https://startpage.com/do/search?query=haskell%20package.yaml) list `sol/hpack` on third position and the SO question second.  I hope over time `sol/hpack` will just bubble to the top.

I'm inclined to close this as "won't fix".  I still think resolving #140 could help a lot.

**Comment by sol** [comment]
Closing.
