### ISSUE TITLE
Suggestion: High-level summary in cabal file and readme

### ISSUE THREAD

**Issue by MichaelXavier** [sol/hpack#140]
Just a suggestion, feel free to ignore. I don't directly use hpack but I depend on a few packages that do so I have to ensure that it runs. Every time I get curious I look it up on hackage and then on github and all I see is a description "An alternative format for Haskell packages" which doesn't really convey any meaningful info to me and then an examples and file format documentation (both of which look great). Might I suggest a brief blurb on both the cabal description and readme that describes the motivating case where you'd use hpack or what problems it solves?

**Comment by sol** [comment]
Yes, sounds great!  We definitely want to have this.  It's missing because `hpack` just naturally grew, and it was never added.

Sadly, I don't have cycles to do it myself.  Any volunteers, @liskin @sjakobi @mitchellwrosen, @yamadapc?

**Comment by mitchellwrosen** [comment]
Here are some differences:

Pro:

- yaml syntax is more ubiquitous than cabal syntax, and less finicky wrt. where commas may be placed, etc
- syntactic sugar such as:
  - `github` field sets both `homepage` and `bug-reports` in cabal file
  - glob patterns for `extra-source-files`, `data-files`, etc
- sets a sensible `cabal-version` automatically
- may specify many top-level fields (such as `dependencies`) that are merged with all components (e.g. if the lib, exes, tests, and benchmarks all depend on `base`, you may put it outside all of them)

And the best pro of all,

- `exposed-modules`/`other-modules` for library are set automatically, given source dirs

Cons:

- Doesn't support all of cabal
- (related to previous) some fields are hard-coded, e.g. test type, cabal version, etc.
- awkward condition syntax

I'm sure someone can put some of this info (and more) into a nice sounding paragraph... but that person probably shouldn't be me :)
