### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by sjakobi** [sol/hpack#149]
It would be great if I could easily tell what changes happened between versions.

I'll be happy with any old changelog that roughly records what happened, but if there's any desire for inspiration, there's http://keepachangelog.com/. :)

**Comment by sol** [comment]
So far a I thought of `hpack` as being early stage, and for that reason this was low on my list of priorities.  But now, almost 2 years into the project and more users, yes, let's keep one.

That is, I'm ok with maintain a changelog for new changes.
