### ISSUE TITLE
Do not include README in cabal package

### ISSUE THREAD

**Issue by sol** [sol/hpack#153]
The rendering on Hackage is broken.  So I guess we better just refer users to GitHub.

**Comment by sol** [comment]
https://hackage.haskell.org/package/hpack#readme

**Comment by liskin** [comment]
I tried to research if this has other solution than removing readme with no good results, but this seems relevant: http://stackoverflow.com/questions/41623846/which-dialect-of-markdown-does-hackage-use-to-render-readmes
Anyway, I did this in #154

**Comment by sjakobi** [comment]
Yeah, the Hackage markdown rendering is a bit of a shame. Relevant issue [here](https://github.com/haskell/hackage-server/issues/565) – I guess I could need a bit of support there.
