### ISSUE TITLE
"ghc-options:" -main-is module for multiple executables

### ISSUE THREAD

**Issue by runeksvendsen** [sol/hpack#158]
I have a `package.yaml` with the following `execitables` section:

```
executables:
  bitcoin-clearing-server:
    main: ClearingServer/Main.hs
    source-dirs: src
  bitcoin-signer:
    main: BitcoinSigner/Main.hs
    source-dirs: src
  note-signer:
    main: NoteSigner/Main.hs
    source-dirs: src
```

If I try to build this as-is, I get an error because `-main-is` module has not been specified to GHC:

```
rune@macbook:~/IdeaProjects/bitcoin-clearing-server$ stack build
Preprocessing executable 'bitcoin-clearing-server' for
bitcoin-clearing-server-0.1.0.0...
[29 of 29] Compiling ClearingServer.Main ( src/ClearingServer/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/bitcoin-clearing-server/bitcoin-clearing-server-tmp/ClearingServer/Main.o ) [flags changed]

<no location info>: error:
    output was redirected with -o, but no output will be generated
because there is no Main module.

--  While building package bitcoin-clearing-server-0.1.0.0 using:
      /Users/rune/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build exe:bitcoin-clearing-server exe:bitcoin-signer exe:bitcoin-signer-arm exe:note-signer --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

If I add the following to the top level of my `package.yaml`

```
ghc-options:
- -main-is
- ClearingServer.Main
```

then `ClearingServer.Main` is successfully built, but now `BitcoinSigner` doesn't work because it thinks its main module is `ClearingServer.Main`:

```
rune@macbook:~/IdeaProjects/bitcoin-clearing-server$ stack build
Preprocessing executable 'bitcoin-clearing-server' for
bitcoin-clearing-server-0.1.0.0...
[29 of 29] Compiling ClearingServer.Main ( src/ClearingServer/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/bitcoin-clearing-server/bitcoin-clearing-server-tmp/ClearingServer/Main.o ) [flags changed]
Linking .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/bitcoin-clearing-server/bitcoin-clearing-server ...
Preprocessing executable 'bitcoin-signer' for
bitcoin-clearing-server-0.1.0.0...

<no location info>: error:
    output was redirected with -o, but no output will be generated
because there is no ClearingServer.Main module.

--  While building package bitcoin-clearing-server-0.1.0.0 using:
      /Users/rune/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build exe:bitcoin-clearing-server exe:bitcoin-signer exe:bitcoin-signer-arm exe:note-signer --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

As far as I can see, for this to work, a section like this:

```
executables:
  bitcoin-clearing-server:
    main: ClearingServer/Main.hs
    source-dirs: src
```

must add `-main-is ClearingServer.Main` to `ghc-options` of the appropriate Cabal `executable` stanza, like so:

```
executable bitcoin-clearing-server
  main-is: ClearingServer/Main.hs
  ghc-options: -main-is ClearingServer.Main
```

If I modify the cabal file produced by hpack to include this additional information, all executables link without problems.

**Comment by liskin** [comment]
Why don't you add
```
ghc-options:
- -main-is
- ClearingServer.Main
```
to `bitcoin-clearing-server:` instead of to top level?

**Comment by sol** [comment]
@runeksvendsen in general, as @liskin mentioned, you can specify `ghc-options on a per-executable basis.

But, in your particular case, you can also specify a module instead of a source fail as `main` and `hpack` will add the required `-main-is` for your. Specifically try:

```yaml
source-dirs: src
executables:
  bitcoin-clearing-server:
    main: ClearingServer.Main
  bitcoin-signer:
    main: BitcoinSigner.Main
  note-signer:
    main: NoteSigner.Main
```

But as a disclaimer, note that GHCs `-main-is` has some limitations.  Specifically, it has to refer to a module in source form.  It can not be a already compiled library module.

**Comment by sol** [comment]
That said, following a layout like e.g. https://github.com/hspec/sensei/blob/ad436d2095f5a36121eac43e0c1fe946e7568215/package.yaml#L34 for multiple executables is more common with GHC and may result in less hassle.

**Comment by runeksvendsen** [comment]
Thank you sirs.

In the back of my head, I think I had the memory of trying to add `main-is` to each entry in `executables`, which didn't work , rather than as part of `ghc-options`. Adding separate `ghc-options` totally works, and just specifyng the `main` class makes it a lot more compact.

By the way, I just discovered `hpack` a month or so ago, and I thoroughly enjoy how it simplifies things over Cabal. I'm pretty sure that my `package.yaml` is at least five times shorter than my `.cabal`, not in the least due to `other-modules`. Keep up the good work!
