### ISSUE TITLE
Remove link to hpack-convert

### ISSUE THREAD

**Issue by ndmitchell** [sol/hpack#170]
The README recommends/suggests hpack-convert. Unfortunately actually installing that with stack is very difficult - see https://github.com/yamadapc/hpack-convert/issues/5. I recommend removing the link to hpack-convert as it gives a bad impression for the moment (I wasted a while trying to install it before giving up and doing it by hand).

**Comment by kanishka-azimi** [comment]
Consider closing this since the author updated hpack-convert.
