### ISSUE TITLE
More source-repository types

### ISSUE THREAD

**Issue by kanishka-azimi** [sol/hpack#171]
For simple completeness, at some point in the future, consider adding the rest of the cabal supported repository types. Hackage documents briefly how it generates checkout commands for various repository types - 

https://github.com/haskell/hackage-server/blob/d5abd9796fc5d00b031052478c00e6b6138a16ab/Distribution/Server/Pages/Package.hs#L516

I wasn't able to find a nice concise chart identifying generic web urls for each type of repo. I would start by adding darcs, mercurial, and svn, through some new field such as "other-source-repo" or similar.

**Comment by sol** [comment]
@kanishka-azimi I'm not inclined to add other repository types unless somebody actually wants to use them.

READ: If you need support for some other RCS, then (and only then) you may open a PR.

This is the general policy I use when adding features, we only add what we need.  "Cabal" supports it is not good enough a reason for us to adopt it.

**Comment by sol** [comment]
I'm closing this as "won't fix", but everybody, please feel free to open PR, given what I stated above is true for you.
