### ISSUE TITLE
Setup.hs, main files?

### ISSUE THREAD

**Issue by kanishka-azimi** [sol/hpack#173]
Maybe offer ability to generate setup.hs for simple build?

Similarly, I often write boilerplate main files that consist of importing another module where main is defined, simply so I can have main.hs in its own hs-source-dir. Might be able to generate that.

**Comment by sol** [comment]
Regarding `Setup.hs`, I have being thinking for that myself for a while already but didn't come to a conclusion yet.  We could generate one, if both

1. neither `Setup.hs` nor `Setup.lhs` is present
1. the build type is not `custom`

**Comment by sol** [comment]
@kanishka-azimi regarding generating a main module, are you aware that you can specify e.g.:

```yaml
executables:
  foo:
    main: Some.Module.someFunction
```
as `main`?

This will pass `-main-is Some.Module.fooTest` to GHC.  When GHC sees a `-main-is` directive, it generates a suitable `Main.hs` transparently.

Does this do what you want?

However, GHC's `-main-is` has one limitation, it only works if the specified module is part of the current compilation unit.  To lift this restriction `hpack` would indeed need to generate that `Main.hs` itself.

**Comment by kanishka-azimi** [comment]
> This will pass -main-is Some.Module.fooTest to GHC. When GHC sees a -main-is directive, it generates a suitable Main.hs transparently.

I am not sure if this is new information or something I already use. I will experiment and review as time allows. I generally create a separate main module in its own directory, to avoid the double compilation issues (that may or may not be still present)

**Comment by sol** [comment]
I created a feature request for GHC: https://ghc.haskell.org/trac/ghc/ticket/13801

**Comment by kanishka-azimi** [comment]
I am not actively waiting on this, so I will close. Feel free to reopen if you were using this to track this task.
