### ISSUE TITLE
Print cabal file to stdout

### ISSUE THREAD

**Issue by Profpatsch** [sol/hpack#176]
For automation purposes I’d like to get the created cabal contents on stdout. It’s very hard to get a reference to that file right now, because the name depends on the name field inside the `package.yaml`, which is kind of arbitrary.

**Comment by sol** [comment]
@Profpatsch Hey, I would like to understand the use case for this?

**Comment by Profpatsch** [comment]
Ah, I solved it in the meantime. The cabal file doesn’t really make sense outside of the source tree, so this request is kind of moot, yes.
