### ISSUE TITLE
Shortcut for "see readme" desc?

### ISSUE THREAD

**Issue by kanishka-azimi** [sol/hpack#179]
Thanks for considering. Feel free to close if this seems of too low value.

**Comment by sol** [comment]
@kanishka-azimi Hey, thanks for taking the time to open this issue!  Can you give a concrete example of what you want to specify in `package.yaml` and what `hpack` should generate from that?

**Comment by kanishka-azimi** [comment]
If github is provided and description is not provided, then set description to: "See README at <repo>#readme". If description is provided, no new default behavior. (Modeled after your hpack example)

**Comment by sol** [comment]
@kanishka-azimi `hpack` embraces *convention over configuration* and in that sense we want to have sane defaults for most of the things.  In this specific case however, I'm still undecided whether this is an established convention that most people want.

**Comment by sol** [comment]
Closing as "wontfix" for now.
