### ISSUE TITLE
Command line interface is not particularly user-friendly

### ISSUE THREAD

**Issue by supki** [sol/hpack#18]
It would be helpful if hpack had shown *anything* when run from the command line, even if it's just `Generating foo.cabal from package.yml` or a usage string. The current behavior is confusing:

```
% hpack
% hpack --help
% hpack help
%
```

**Comment by sol** [comment]
I guess this is a reasonable request.  What exactly do you suggest?  Can you send a PR?

**Comment by supki** [comment]
Sure, #20
