### ISSUE TITLE
hpack doesn't see dependency

### ISSUE THREAD

**Issue by denisshevchenko** [sol/hpack#180]
I'm testing `hpack` with `stack`.

I have standard project: library + executable that use this library. But when I specify dependency from this library, `stack build` gives me an error:

```
Main.hs:17:1: error:
    Failed to load interface for    BreadU
    It is a member of the hidden package    breadu-0.3.1   .
    Perhaps you need to add    breadu    to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

It's really strange, because I have that dependency in my `package.yaml` and even see that dependency in generated `.cabal`-file! 

```
library:
    source-dirs:      src/lib
    exposed-modules:
        - BreadU 
    default-extensions:
        - RecordWildCards
        - OverloadedStrings
        - MultiWayIf
        - ViewPatterns
    ghc-options:      -Wall -Werror -Wno-orphans -O

executables:
    breadu-exe:
        main:           Main.hs
        source-dirs:    src/app
        ghc-options:    -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O
        dependencies:
            - breadu
```

How can I fix it? I'm using these tools:

- stack 1.4.0,
- LTS Haskell 8.18,
- Ubuntu 16.04.2.

**Comment by sol** [comment]
Hey!  Thanks for taking the time to open this issue.

I don't see anything wrong with the `package.yam` you provide.

Can you push what you have to some branch so that I can take a look at it?

**Comment by denisshevchenko** [comment]
https://github.com/denisshevchenko/breadu.info/blob/Hpack/package.yaml

**Comment by liskin** [comment]
@denisshevchenko Aren't you just missing the `breadu` dependency for the `update-breadu-server` executable?

(Alternatively, perhaps you misspelled `main` or `source-dirs` for `update-breadu-server`, as it seems strange to build the same binary twice.)

**Comment by denisshevchenko** [comment]
> @denisshevchenko Aren't you just missing the breadu dependency for the update-breadu-server executable?

@liskin Of course, because `update-breadu-server` doesn't use `breadu`. :-) Only `breadu-exe` uses `breadu` lirary.

**Comment by liskin** [comment]
@denisshevchenko It's the same source file as `breadu-exe`. How come one doesn't use `breadu` and the other does? It makes no sense. :-(

**Comment by denisshevchenko** [comment]
Wait. I see this:

```
executables:
    # BreadU server.
    breadu-exe:
        main:           Main.hs
        source-dirs:    src/app
        ghc-options:    -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O
        dependencies:
            - breadu
    # BreadU server updater (using during CI).
    update-breadu-server:
        main:           Main.hs
        source-dirs:    src/app
        ghc-options:    -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O
```

`executables`, not `executable`, right? I'm trying to define two different executables here. Is it possible? Or I have to change it like this?

```
executables:
    # BreadU server.
    breadu-exe:
        main:           Main.hs
        source-dirs:    src/app
        ghc-options:    -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O
        dependencies:
            - breadu

executables:
    # BreadU server updater (using during CI).
    update-breadu-server:
        main:           Main.hs
        source-dirs:    src/app
        ghc-options:    -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -O
```

**Comment by denisshevchenko** [comment]
Nope, it doesn't work too. :-(

**Comment by denisshevchenko** [comment]
As I said, I have to build two different executables, and only one of them depends on `breadu` library.

**Comment by sol** [comment]
@denisshevchenko As @liskin pointed out, the executable section for `update-breadu-server` is most likely the issue.  You either have to add `dependencies: breadu` to it OR change `main:` to something different than `Main.hs`.  Currently `breadu-exe` and `update-breadu-server` are *exactly the same, exception for `update-breadu-server` the dependency on `breadu`.

**Comment by denisshevchenko** [comment]
Aaaaaah... I copied `source-dirs:    src/app` instead of `source-dirs:    src/update`. Sorry, guys.
