### ISSUE TITLE
Parse * as AnyVersion when parsing constraints

### ISSUE THREAD

**Issue by sol** [sol/hpack#201]

**Comment by sol** [comment]
Not that useful, as `*` needs quoting in YAML.  So I guess using one of the existing options, e.g. `null` is preferable.

**Comment by tfausak** [comment]
Now that #199 has been merged, won't `foo: '*'` be interpreted as `foo ==*`? Sadly Cabal won't parse that (it requires at least one version component, like `foo ==1.*`), but if it did then this could be supported without any extra work from hpack.

**Comment by sol** [comment]
@tfausak Yes, surprisingly `Cabal` won't accept `*`.  So my original intention with this issue was to implement it in `hpack`.

**Comment by tfausak** [comment]
Yeah it surprised me that Cabal doesn't support `==*`. I opened an issue for it: https://github.com/haskell/cabal/issues/4802. As far as hpack is concerned, I think `foo: null` or just `foo:` is fine.

**Comment by sol** [comment]
> As far as hpack is concerned, I think `foo: null` or just `foo:` is fine

Yes.  I would love `*`, but I hate that it needs quoting.  So far I was not eager to add `x` as an alias for `*` (their should be one obvious way to do things), but `x` would at least not need quoting..
