### ISSUE TITLE
cabal-version field

### ISSUE THREAD

**Issue by shlevy** [sol/hpack#204]
We have some custom Setup.hs that depends on Cabal 2, which we'd like to specify as a minimum for cabal-version in our cabal files.

**Comment by sol** [comment]
@shlevy Hi Shea, long time no talk.  I'm not too excited to add `cabal-version`, but it seems you have a valid use case.

Do you want this for a public package or an internal project?  If it's internal, I would try to convince you to solve it with a team policy.  If it's public we probably want to address it in `hpack`.

**Comment by sol** [comment]
Maybe too far fetched, but would be awesome if we could infer it somehow, e.g. `Setup.hs`.

**Comment by shlevy** [comment]
Hey Simon! Somehow didn't make the connection with your username, nice to chat!

Not sure what you mean by "team policy" here? Just telling everyone to use Cabal 2 themselves?

**Comment by sol** [comment]
@shlevy Shea, sorry for the late reply.

`hpack` might already address your use case.  Please try to add

```yaml
custom-setup:
  dependencies: Cabal == 2.*
```

to `package.yaml`.  Does this work and solve your use case?

> Not sure what you mean by "team policy" here? Just telling everyone to use Cabal 2 themselves?

Yes basically, ideally in terms of code (dependency freezing or nixpkgs).

**Comment by shlevy** [comment]
Hi Simon,

Yeah, we needed to add that eventually to get stack working, but IIRC the error message when you use Cabal 1.x there was confusing. Anyway, this gets us most of what we want.

**Comment by sol** [comment]
@shlevy I guess this is actually a bug.  I opened #210.

**Comment by sol** [comment]
This is possible by now with:

```yaml
verbatim:
  cabal-version: 2.2
```
