### ISSUE TITLE
Feature request: support `autogen-modules` field

### ISSUE THREAD

**Issue by TerrorJack** [sol/hpack#207]
[autogen-modules](https://cabal.readthedocs.io/en/latest/developing-packages.html#autogenerated-modules) is present in `Cabal-2.0.0.2`, and is useful for representing modules generated by custom `Setup.hs` scripts.

**Comment by sol** [comment]
@TerrorJack Thank for opening this issue.  I'm more than willing to accept a PR for this.  But we may not want to clone exactly what Cabal does here.  Specifically, specifying the same module in both `autogen-modules` and `exposed-modules` or `other-modules` is not DRY.  So we may want to have e.g. `generated-modules` and `generated-exposed-modules` instead (or would it be `exposed-generated-modules`) and then add these modules to both Cabal's `autogen-modules` and `other-modules` or `exposed-modules` respectively.
