### ISSUE TITLE
Doesn't build on GHC < 7.8

### ISSUE THREAD

**Issue by bergmark** [sol/hpack#22]
I've revised existing versions: http://hackage.haskell.org/package/hpack/revisions/

A new release is needed if you wish to restore backwards compatibility, otherwise I recommend adding a `base >= 4.7` lower bound.

**Comment by sol** [comment]
We have the lower bound in `package.yaml` by now.  Patches for older versions of `base` are welcome, but as `hpack` is still experimental, it's not on my list of priorities.  Closing.
