### ISSUE TITLE
Warn on `extra-source-files` which don't exist

### ISSUE THREAD

**Issue by Fuuzetsu** [sol/hpack#23]
As in subject. We can do this fairly easily so I wonder if it makes sense for `hpack` to do so.

I think cabal warns itself later so if `hpack` is going fairly strictly for just translating yaml -> cabal then it's not that important. OTOH hpack already warns on missing source dirs…

**Comment by Fuuzetsu** [comment]
Actually it seems that if we introduce globbing, warnings become pretty necessary anyway because it's hard to decide between whether a user put in a file path which doesn't exist or a glob which doesn't match anything.

**Comment by sol** [comment]
Fixed on master.
