### ISSUE TITLE
Allow version to be a number?

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#263]
Currently the `version` field must be a string. If you want to use a version number like `12` or `3.4`, you must quote it (see #44). Otherwise you'll see an error like this:

``` yaml
# package.yaml
name: example
version: 0
```

```
.../package.yaml: Error in $.version: expected String, encountered Number
```

I think it would be nice to accept numbers as versions. That way `version: 12` and `version: 3.4` would work, which feels right because `version: 5.6.7` (without quotes) works today. 

The only problem I can think of is that leading zeros would not make it to the Cabal file. In practice I don't think this is a problem because Cabal parses each version component as a number, which ends up stripping leading zeros anyway.

**Comment by quasicomputational** [comment]
I know JSON's numbers are under-specified, but are YAML's? I'd be concerned about winding up relying on the yaml package's parsing behaviour when other parsers could differ.

**Comment by quasicomputational** [comment]
Oh, actually, this is already implemented in HEAD by commit d56cc8ed8dc0971f326e4e7e0084aa0749363b4b. I wonder how it deals with the (non-)difference between `42` and `42.0`...

**Comment by sol** [comment]
> I wonder how it deals with the (non-)difference between 42 and 42.0...

It is format preserving, except for if you use leading zeros or `e`-notation, that is we can figure out the difference between `42` and `42.0`.

**Comment by sol** [comment]
Closing, as it is already implemented and part of the next release.

**Comment by tfausak** [comment]
:tada: Great!
