### ISSUE TITLE
Discussion: Make a smallest working example of package.yaml easily obtainable.

### ISSUE THREAD

**Issue by kindaro** [sol/hpack#269]
I don't want to remember what fields I must specify when I want to create a new package. So, I end up looking for an existing `package.yaml` and copying from there. Therefore, I have a twofold proposition:

1. Add a "*quick start*" section to `readme`, that would list a sample `package.yaml`, suitable for instantiating a simple project.
2. Add an `init` command line option that outputs the same sample `package.yaml` to standard output, filling the `name` field with current directory name.
    * Let the user define a custom `package.yaml` template in `~/.hpack/package.yaml`.

I think it would be a nice feature to have.

**Comment by tfausak** [comment]
I know it's not what you meant, but the smallest `package.yaml` is an empty record: `{}`. The package name is inferred from the directory name, so `some-project/package.yaml` will automatically give `name: some-project`. The version number defaults to `0.0.0`, build type to `Simple`, and Cabal version to `>= 1.10`. 

That being said, I think a quick start section in the documentation would be great. As it is now, the documentation is more like a reference than a tutorial. Slides aren't my favorite way to learn things, but hpack's introductory slides are good and to the point: <http://typeful.net/talks/hpack/>

Also the first example `package.yaml` belongs to hpack itself and is, while not exactly minimal, pretty straightforward: <https://github.com/sol/hpack/blob/0.25.0/package.yaml>.

hpack doesn't have templating built in, but you can use Stack to start new projects. Many of the Stack templates use hpack. For example, `stack new simple-hpack`. <https://github.com/commercialhaskell/stack-templates/blob/cd567d5/simple-hpack.hsfiles>

**Comment by kindaro** [comment]
@tfausak, thanks for commenting. From my initial posting, the motivation of my wish must not yet be clear, so I will elaborate on it in a few sentences below.

The principal use case of `hpack` per se (as a command line tool) for me is when I have some random haskell sources stacked up in a folder, and some day I decide it's time to turn them into an actual package. Then I will either:
* be running `cabal init`, followed by `hpack-convert`, or 
* copy a `package.yaml` from some other recently packaged project of mine, that will customarily have some nice flags set (such as `ghc-options: -Wall -Wno-name-shadowing`).

What I want is the latter way made official. I will then put all my favourite options to a `~/.hpack/package.yaml` and then simply cast `hpack init` on a folder to "package" it.

I don't usually use `stack new` for starting new projects. I find it uncomfortable. I would rather have a `{}` `package.yaml` at first, and extend a project as needed, organically.

Please tell me if it makes more sense now.

**Comment by sol** [comment]
@kindaro thank you for taking the time to open this issue!  I think this issue is similar enough to #187 that it makes sense to combine them.  Please feel free to add your input to the existing discussion. I'll close as `duplicate`.
