### ISSUE TITLE
Lower bounds on Aeson appear to be insufficient.

### ISSUE THREAD

**Issue by seanparsons** [sol/hpack#270]
In this file:
https://github.com/sol/hpack/blob/11d9d15b4d00acdb03919f6408dd9ecfdb1e2274/src/Data/Aeson/Config/Parser.hs#L109
`parserCatchError` from Aeson is being used.

However according to the docs for Aeson:
https://hackage.haskell.org/package/aeson-1.2.4.0/docs/Data-Aeson-Types.html#v:parserCatchError
That has only been available since version 1.2.1.0

But hpack only has `aeson >= 1.0.0` specified which means there are a window of versions that wont have that function in that gap.

For me this manifested with this error:
```
/run/user/1000/stack17443/hpack-0.25.0/src/Data/Aeson/Config/Parser.hs:109:24: error:
        Not in scope: `Aeson.parserCatchError'
        Neither `Data.Aeson.Internal' nor `Data.Aeson.Types' exports `parserCatchError'.
```

**Comment by sol** [comment]
@seanparsons nice catch!  I messed this up somehow.  What we of course can and should do is add the lower bound.  Is that everything you need, or do you actually need to build `hpack` with an older version of `aeson`?  If the it's the later, that is tricky, as we need `parserCatchError` warn on unrecognized fields (it's the only exposed way to get hold of the path).

**Comment by sol** [comment]
Fixed on Hackage and `master`.

**Comment by seanparsons** [comment]
For me I was able to get around it with a stack.yaml file so no special shenanigans are needed thanks.
