### ISSUE TITLE
Default cycle detection isn't perfect (and can't be)

### ISSUE THREAD

**Issue by quasicomputational** [sol/hpack#274]
Silly games like symlinks to directories or bind mounts can defeat the cycle detection and we've got no good way to identify when that happens. Emphasis on the 'silly'. I don't think it's worth trying to DTRT in these situations, but it's currently possible to set up a pathological environment and have hpack sit there and spin for a long time; maybe it would make sense to put a (configurable?) cap on how many layers of defaults hpack will look through?

**Comment by sol** [comment]
> spin for a long time

I'm puzzled what this exactly means.  My assumption is that `hpack` is guaranteed to terminate, either by detecting a cycle or by succeeding. If that is not the case, I would want to see test case that illustrates the issue.

As a side note, does it matter for this discussion how a user creates cycles?  Is there any fundamental difference between creating a symlink and creating the same file twice (or mounting the same volume multiple times)?  Symlinks may even aid the cycle detection they are resolved by `canonicalizePath`, which we use in the cycle detection code.

> maybe it would make sense to put a (configurable?) cap on how many layers of defaults hpack will look through?

For e.g. a webservice where untrusted users provide input I would say possibly (but even here simpler means, like hard limits on the request size may be more effective).  For `hpack` I'm not convinced yet.

**Comment by quasicomputational** [comment]
Oh, huh. I had the impression I could create a loop with bind mounts, but that's not the case! It might be possible with some FUSE trickery, but I think that that would be extra silly to do. I think this issue's probably irrelevant, then.
