### ISSUE TITLE
Module Blacklisting: excluding experimental module from both `exposed-modules` and `other-modules`

### ISSUE THREAD

**Issue by konn** [sol/hpack#278]
Is there any way to *blacklisting* modules, i.e. to exclude specific module from both `exposed-modules` and `other-modules`?

This is useful when we develop some experimental functionalities in specific module, e.g. `Lib.Great.New`, but we don't want it to compiled.

**Comment by sol** [comment]
The only ways to achieve this is by either specifying both `exposed-modules` and `other-modules` explicitly or by placing that "experimental" module into a separate source directory.

**Comment by sol** [comment]
This is a question that has been answered.  I'm closing this issue.  If you want any specific changes to `hpack` then please open a separate issue for that.
