### ISSUE TITLE
Last-one-wins clobbering behaviour for top level sections

### ISSUE THREAD

**Issue by Fuuzetsu** [sol/hpack#283]
This surprised me

```
[shana@lenalee:/tmp]$ hpack package.yaml 
generated abc.cabal

[shana@lenalee:/tmp]$ cat abc.cabal 
-- This file has been generated from package.yaml by hpack version 0.21.2.
--
-- see: https://github.com/sol/hpack
--
-- hash: 525dbe7a340841f69420818cb6efcf419ea6279793347bd04bbedae11fbc67a5

name:           abc
version:        0.1.0.0
synopsis:       abc
description:    abc
category:       Network
author:         Mateusz Kowalczyk
maintainer:     fuuzetsu@fuuzetsu.co.uk
copyright:      2018 Mateusz Kowalczyk
license:        AllRightsReserved
build-type:     Simple
cabal-version:  >= 1.10

benchmark bench2
  type: exitcode-stdio-1.0
  main-is: Bench2.hs
  other-modules:
      Paths_abc
  hs-source-dirs:
      bench2
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.7 && <5
  default-language: Haskell2010

[shana@lenalee:/tmp]$ cat package.yaml 
name: abc
version: 0.1.0.0
license: AllRightsReserved
author: "Mateusz Kowalczyk"
maintainer: "fuuzetsu@fuuzetsu.co.uk"
copyright: "2018 Mateusz Kowalczyk"
synopsis: abc
category: Network
description: abc

dependencies:
- base >= 4.7 && < 5

benchmarks:
  parse-quote:
    main:                Bench1.hs
    source-dirs:         bench1
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    - -fwarn-identities
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

benchmarks:
  bench2:
    main:                Bench2.hs
    source-dirs:         bench2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
```

Of course once I thought about it, the fix is

```
benchmarks:
  parse-quote:
    main:                Bench1.hs
    source-dirs:         bench1
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    - -fwarn-identities
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

  bench2:
    main:                Bench2.hs
    source-dirs:         bench2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
```

However it's often not instantly clear why your benchmark doesn't seem to exist and you need to chase it down to hpack.

I would like to request one of these scenarios:
* merge the sections without warning
* error out
* don't merge sections and warn the user
* merge sections and warn the user

I expect this behaviour is unintended and simply the result of how parsing is performed.

**Comment by Fuuzetsu** [comment]
I also suspect it's not only the case for top-level things so ideally this would be applied more universally.

**Comment by quasicomputational** [comment]
This is sort of not hpack's problem, since duplicate keys are undefined behaviour in YAML. I agree that not silently ignoring the duplicates would be desirable, but that'll need changes in the yaml package. Having had a peek, [`parseM` in `Data.Yaml.Internal`](https://github.com/snoyberg/yaml/blob/7ce90970adb3b278dffb2d5e4ac724bfe59db768/Data/Yaml/Internal.hs#L216) is a likely place to start, but whoever implements it would have to work out the nitty-gritty of actually reporting the warnings sanely.

**Comment by Fuuzetsu** [comment]
Yeah I figured, it's more or less what I meant by "result of how parsing is performed". Using a different parser or whatever the solution might be here to reject undefined YAML would be fine.

**Comment by sol** [comment]
I agree that warnings would be useful, but that would require changes to `yaml`.  We can consider this when/if `yaml` supports this.  But for now this is a `wontfix`.

**Comment by sol** [comment]
I'm looking into this again.

**Comment by Fuuzetsu** [comment]
Neat, thanks.
