### ISSUE TITLE
stylish-haskell config generator

### ISSUE THREAD

**Issue by kana-sama** [sol/hpack#284]
How about generation stylish-haskell config from hpack config? My main proposal is to generate `language_extensions:` from `default-extensions`.

**Comment by sol** [comment]
@kana-sama Hi, thanks for taking the time to open this issue!

> How about generation stylish-haskell config from hpack config?

The is out of Hpack's current scope.  But let's assume, as a thought experiment, that we widen the scope of Hpack to include this.  When exactly would we generate `.stylish-haskell.yaml`?  Every time `hpack` is run or only when a specific flag is passed, e.g. `hpack --stylish`?  If always, then what if there is already a `.stylish-haskell.yaml`?

**Comment by kana-sama** [comment]
Ok, all in all it is a bad idea, I have no good answers on your questions. Maybe there are other solutions for the same extensions list in different configs (hlint, stylish, hpack).

**Comment by sol** [comment]
@kana-sama here is a way to reduce the duplication:

In `.stylish-haskell.yaml` define your language extensions like this:

```yaml
language_extensions: &language-extensions
  - DeriveGeneric
  - LambdaCase
  - NamedFieldPuns
  - FlexibleContexts
  - ViewPatterns
  - QuasiQuotes
```

Then in `package.yaml` you can import them:

```yaml
_includes:
  - !include .stylish-haskell.yaml

default-extensions: *language-extensions
```
Hope that helps!
