### ISSUE TITLE
Given a cabal file is there an automatic conversion to package.yaml?

### ISSUE THREAD

**Issue by CMCDragonkai** [sol/hpack#286]
Question in title.

**Comment by CMCDragonkai** [comment]
Hopefully that could become part of stack.

On 26 April 2018 02:21:39 GMT+10:00, Taylor Fausak <notifications@github.com> wrote:
>Yes, use `hpack-convert`. See #107.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sol/hpack/issues/286#issuecomment-384347050

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sol** [comment]
In the past @mgsloan and others suggested to make this part of `hpack`.  Even though I see how this would be beneficial, I currently don't have the bandwidth to maintain such a tool.  So using `hpack-convert` is all we got for now.
