### ISSUE TITLE
Regression: null keys in package.yaml break parsing

### ISSUE THREAD

**Issue by tejon** [sol/hpack#288]
Empty keys in package.yaml used to be fine, now they cause the parser to fail. Trivial example:
```yaml
license:
# Error while parsing $.license - expected String, encountered Null
```
This applies to nested keys as well.

Not sure when this happened, i just discovered it when my heroku buildpack pulled in stack-1.7.1.

**Comment by sol** [comment]
I'm closing this as `wontfix`.  That said, I'm still interested in dissenting opinions.  If there is a good case for restoring the old behavior then it is easy to convince me.

**Comment by sol** [comment]
@tejon thank you for bringing this to my attention and sorry for the friction this might have caused.
