### ISSUE TITLE
Extra-deps ?

### ISSUE THREAD

**Issue by checkraiser** [sol/hpack#290]
In `stack`, i can use `extra-deps` to build from github, but how to do that with `hpack` ?

**Comment by quasicomputational** [comment]
There's nothing special about `extra-deps` from hpack's point of view: they're Haskell packages that you can put in your `dependencies`. [Stack has some documentation that may be helpful.](https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/)
