### ISSUE TITLE
Proposal: module hiding and renaming parts of mixins

### ISSUE THREAD

**Issue by quasicomputational** [sol/hpack#318]
The [`mixins`](https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-mixins) field is useful for renaming and hiding (or selectively exposing) modules from dependencies, even without supporting the full power of backpack. To use it today with hpack, you need to use `verbatim`, and it's awkward in a couple of ways:

* You have to repeat the package in the `depends` field as well as the verbatim `mixins` field. Those two are not necessarily close together, increasing the chance of bugs.
* Some of Cabal's syntax isn't great; e.g., to get renaming plus default passthrough, you have to write two lines: `foo (Bar as Baz), foo hiding (Bar)`.
* You likely have to remember to set the right `cabal-version` with `verbatim`.

I think hpack could usefully support the module renaming/hiding parts and punt on supporting `requires`; with `verbatim`, anyone who needs that power has an escape hatch to get at it.

My proposed syntax is this: we extend object dependencies to take an object instead of just a string version, leading to something looking like this:

```
  depends:
    base:
      version: ">= 4.10.1.0 && < 4.12"
      renaming:
        - from: Some.Long.Name
          to: Short
      hiding:
        - A
    blah:
      exposing:
        - Blah
```

This will generate something like this:

```
  build-depends:
    base >= 4.10.1.0 && < 4.12,
    blah
  mixins:
    base (Some.Long.Name as Short),
    base hiding (A),
    blah (Blah)
```

It would be an error to have both `hiding` and `exposing` keys. The default should be to expose all modules of the dependency, even if some modules are renamed; `exposing: []` can be written if the opposite behaviour is wanted.

I'm up for implementing this, but I'd like to hear if anyone thinks this design or the UX could be improved.

**Comment by sol** [comment]
@quasicomputational hey, thanks for opening this issue.  Upfront, do you have a use case for this in some actual package?  If yes, is the code public?

**Comment by quasicomputational** [comment]
I specifically want to be able to write `mixins: base hiding (Prelude)` and then swap in my own custom batteries-included `Prelude`. [Here's one of my `package.yaml`s that does that.](https://github.com/quasicomputational/mega/blob/master/packages/xml-core/package.yaml). The `renaming` part is useful if the replacement prelude wasn't called `Prelude` (e.g., you might want `mixins: universum (Universum as Prelude)` instead).

**Comment by sol** [comment]
Ok, that is actually neat.

Syntax wise, I actually like what Cabal does (except for the WETness of course).  Not sure how, but would be nice to build on top of that.

BTW, do you know if it is possible to load a package that uses renaming or hiding of modules into `ghci`?

**Comment by sol** [comment]
> The default should be to expose all modules of the dependency, even if some modules are renamed

How would you want to map this to `.cabal`?

```yaml
dependencies:
  foo:
    renaming:
      from: Foo
      to: Bar
```

then become

```
mixins:
  foo (Foo as Bar)
  foo hiding (Foo)
```
?

**Comment by quasicomputational** [comment]
RE syntax, happy to take suggestions. I'd suggest that we keep an unpacked, YAML-ish syntax as well as anything more compact that we come up with, though.

RE the specific example: yeah, you have it spot on there. Cabal interprets `mixins: foo (Foo as Bar)` as meaning *only* expose the new `Bar`, but I think it's more consistent to have the user explicitly opt in to default-hide than to couple renaming with that.

RE ghci: `cabal new-repl` works like a charm, I can happily report.

**Comment by sol** [comment]
> RE ghci: `cabal new-repl` works like a charm, I can happily report.

If you have a test suite that depends on your library component then `:reload` does not reload the library component, rendering it unsuitable for TDD.  This is the reason why I personally never got any value out of `cabal repl`.  Do you have a way to deal with this?  Or how does your testing setup look like?

**Comment by sol** [comment]
@quasicomputational thanks for opening #321.  Before giving this a review I would still want to allow some more time for discussing:

- the concrete syntax
- how this might interact with adding support for `mixins` later on
- possibilities to address `mixins` right away

@quasicomputational I'm sorry that I'm the bottleneck here.  I'll try to keep up with this.  BTW, if you have spare cycles, I'm still looking for a volunteer to review https://github.com/sol/hpack/pull/316.  It's somewhat biggish.

**Comment by sol** [comment]
> It would be an error to have both `hiding` and `exposing` keys

I would prefer if it were impossible to syntactically represent invalid combinations.

**Comment by sol** [comment]
@quasicomputational do you know what the state of Backpack on Hackage is?  Will it be possible to upload packages that use `mixins`?

**Comment by quasicomputational** [comment]
Hmm. Do you (or anyone else) have any ideas about how `exposing` / `hiding` should be written? The difficulty is that they *are* two incompatible modes of operation and I don't see how to have that without having two mutually exclusive keys.

One syntax idea I had to make it a bit less verbose was that `renaming` could accept a list of strings of the form `$FROM as $TO`. Then renaming could be written very compactly, as `renaming: [A as B, C as D]`.

RE GHCi: I don't run tests from GHCi, no. I only tend to load up GHCi when I want to poke around with types; otherwise I compile/run tests from emacs. And, yeah, `:reload` doesn't quite do what you'd want it to. I'd note, though, that this is independent of backpack except that you'd need to use `cabal new-repl` (or the stack equivalent, which I have never managed to get to work), but I'm already forced into that for other reasons.

RE mixins: Hackage accepts them, yep. See, e.g., [`unpacked-containers`](http://hackage.haskell.org/package/unpacked-containers-0/unpacked-containers.cabal).

I don't *think* that this design is going to step on any future back-hpack plans. My understanding of backpack is maybe not 100% complete and I've never legitimately used it, so this is caveated.

The only things really missing are the `requires` clause, to allow fine control over what signatures the mixin sees, and, with that, multiple instantiations with different sets of signatures. So the user might have something like this, which is more or less using the full power of backpack:

```
mixins:
  foo (Foo as FooA) requires (SigA as Sig),
  foo (Foo as FooB) requires (SigB as Sig),
  foo (Foo as FooC) requires (SigC as Sig)
```

For back-hpack, the above might be written something like this:

```
dependencies:
  - name: foo
    mixins:
      - requiring:
        - SigA as Sig
      - renaming:
        - Foo as FooA
      - exposing: []
(etc)
```

Then the current syntax, with the `renaming` / `exposing` / `hiding` at the dependency level would become syntactic sugar for `mixins` with an empty `requiring`. Or maybe we'd add a dependency-level `requiring` field as well, and make single instantiations really easy to write, since that's likely to be the most common case by a wide margin. Possibly `mixins` entries should be default-hide. Little details like that would need to be resolved, but I think the broad strokes of the extension is clear enough.

I've had most of this in mind when I've been looking at this and trying to design with extensibility in mind, but, like I said, I don't feel like I have a firm enough grip on backpack to say definitively that this would be The Way To Go, and module renaming/hiding is valuable enough that I think it's worth having even without backpack's full featureset.

RE reviews: no rush! I know you do get round to these eventually. I shall have a look at that other PR and see if I have anything useful to say. Thanks for having a preliminary look as it is!

**Comment by sol** [comment]
Let's address the general `mixins` case first.  This will already provide a solution for your use case.  We can then still discuss if we need additional sugar on top of that.

>```
>dependencies:
>  - name: foo
>    mixins:
>      - requiring:
>        - SigA as Sig
>      - renaming:
>        - Foo as FooA
>      - exposing: []
>```

Hmm,  would that really work? What if I list multiple things under `requiring` and/or `renaming`?  How would we want to desugar this to `.cabal`?

**Comment by sol** [comment]
Did you mean:

```yaml
dependencies:
  - name: foo
    mixins:
      - requiring:
        - SigA as Sig
        renaming:
        - Foo as FooA
        exposing: []
```

(note the removed dashes)

**Comment by sol** [comment]
I was just playing around with `mixins` and here is what I observed (in addition to what is described at https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-mixins).

`hiding` can be combined with `requires`:

```
mixins: unpacked-containers hiding (Map) requires (Key as Int)
```

In general, as I understand it, every signature of a package has to be provided before you can use that package, even if you are not using any modules that depend on a signature.

**Comment by quasicomputational** [comment]
Oops, yes, I did bungle the YAML syntax there but you managed to decipher it.

And, yes, `hiding` can be combined with `requires`. Those two would be independent of each other. For each dependency package, there'll only be one instantiation that gets imported as default-expose, though, or else there'd be conflicts. So maybe we want to have the dependency-level instantiation be special in that it's allowed to have `hiding` and then the elements of `mixins` aren't?

And you've got a good point that the `requiring` field would have the same signatures being filled in for each instantiation. Maybe we want to think about inheritance here? But, on the other hand, since it would be a failure if you didn't supply a full set of signatures, I think we could get away with punting this as a 1.0 and seeing how it works out in practice.

**Comment by sol** [comment]
I don't particularly like what Cabal does here, nor am I 100% convinced of any of the alternatives we discussed.

In a situation like this I go with what Cabal does.  Even though I don't like it, at least we don't invent something new.

So the least ambitious approach would be something like:

```yaml
dependencies:
  - name: foo
    mixin:
      - (Foo as FooA) requires (SigA as Sig)
      - hiding (Bar)
```
That is we just DRY up things by not requiring the package name.  Other than that we follow exactly what Cabal does.

As I understand it, the main disadvantage is that the renaming case requires two lines.  It's not nice, but it's possible to tuck it away in some `defaluts` definition.

Going with Strings first has the advantage that we can easily extend it in the future if we come up with something that we like better.

**Comment by sol** [comment]
If you insist, you can convince me to add:

```yaml
dependencies:
  - name: foo
    rename:
      - Foo as Bar
```
which desugars to the two corresponding `mixin` lines.

**Comment by quasicomputational** [comment]
I'd be OK with the bare-bones solution, since that doesn't preclude any kind of future cleverness, like you say. I don't personally care too much about the renaming case so let's say that just simple list-of-strings `mixins` is enough for a 1.0. I'll go and prepare a PR for that at some point soon.
