### ISSUE TITLE
`cabal check` warns on Hpack generated .cabal files due to cabal-version

### ISSUE THREAD

**Issue by sol** [sol/hpack#322]
When Hpack generates a `.cabal` file it will use `>=` syntax for `cabal-version` up to `2.0`.  Only starting from `2.2` it will use `cabal-version: x.y`, as this is required by `Cabal` starting from `2.2`.

This is the most compatible option, but it produces a warning on `cabal check`:

> * Packages relying on Cabal 1.12 or later should specify a version range of
the form 'cabal-version: x.y'. Use 'cabal-version: 2.0'.

Should we always use `cabal-version: x.y` to make the generated `.cabal` file `cabal check` sane?

**Comment by quasicomputational** [comment]
Why not have it generate '>=' when the version is below 1.12, and the bare number above? i.e., the same as now, except we just change the threshold.

**Comment by sol** [comment]
Yes, I think that sounds good.

The disadvantage of this approach is that pre `1.12` versions of Cabal will fail with a parse error instead of a descriptive error message when they encounter `cabal-version: x.y`. But this is something we may want to accept.

**Comment by sol** [comment]
We may also use `1.12` as the lowest `cabal-version` generate.  This will simplify things and I doubt that anything smaller `1.16` is still in use anywhere.

**Comment by quasicomputational** [comment]
Yeah, I doubt that many projects supporting GHC 7.0 are using hpack, and anything older than that isn't supported by even vaguely recent Cabals. Stack only supports 7.8 onwards, which corresponds to Cabal 1.22.
