### ISSUE TITLE
What is Paths_app?

### ISSUE THREAD

**Issue by chrissound** [sol/hpack#343]
I've just tried to use another local package as a dependency with stack but it seems hpack generates a `Paths_app` which results in an error of: 

```
Loading stack ghci --ghci-options='-fdiagnostics-color=always' ...
The same package name is used in multiple local packages

app used in:
- PLOther (PLFilePath "/home/chris/Haskell/NiobiumCoconut")
- PLOther (PLFilePath ".")
```

What is this module doing? Is it possible to exclude to resolve the above error?

**Comment by sol** [comment]
Hey! Thanks for reporting this!

> hpack generates a `Paths_app` which results in an error of

I don't see a reference to `Paths_app` in that error message.

> What is this module doing? Is it possible to exclude to resolve the above error?

`Paths_*` is generated by `Cabal` (first google hit on the topic http://neilmitchell.blogspot.com/2008/02/adding-data-files-using-cabal.html).

You can prevent `hpack` from including `Paths_*` in your package description by specifying `other-modules` manually (in the simplest case just `other-modules: []`).

See also https://github.com/sol/hpack/issues/303.

**Comment by chrissound** [comment]
Apologies this does not seem to be related to `Paths_app` or hpack, I assumed the PLOther  related to Paths_app - but just seems like verbose error. Thank you for your response! :)

To anyone else that has stumbled upon this: 
It's to do with the package name (in my case `app`) being used in both of the packages.
