### ISSUE TITLE
how to specify a resolver? add a keyword

### ISSUE THREAD

**Issue by andrewufrank** [sol/hpack#357]
I have used `.cabal` with stack and try to switch to hpack (`stack init`) but do not see a way to fix a resolver in the `package.yaml` file. Is this intentional? I experience with a new project that I fill in the `package.yaml` file and then `stack init` is selecting a resolver without my control (for some  other reasons, I want to stay with a specific resolver for this project). Where do I specify it? Why not have a `resolver` entry in the `package.yaml` file? 
A replacement for the `.cabal` files is a good idea, but I wish it would have all descriptions I need to fix at the start of a project.

**Comment by quasicomputational** [comment]
[The Stack documentation](https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/) covers exactly this topic, and it's quite intentional. `package.yaml` is per-package; `stack.yaml` is per-project (i.e., can be shared between many packages). If you want a specific resolver, edit `stack.yaml. and set it there.

**Comment by andrewufrank** [comment]
I would have appreciated a per-package replacement of `.cabal` . So far I have not been able to share `stack.yaml` for multiple packages (there is always a difference...). As stack produces the `.cabal` from the `package.yaml` and then the `stack.yaml` from the cabal, I observe a 1 to 1 relation between 'package.yaml' and 'stack.yaml' - having to produce the `stack.yaml` first (which may take a while to install a compiler etc. etc.) and then to edit the `stack.yaml` later is distributing info   for one package between two files and asks for confusion, subtle bugs and all the rest...
For those, that share a `stack.yaml` (or edit it), nothing is lost with a "resolver" entry in the `package.yaml` (neither for those who do not use stack), but for simple projects it makes it worth to learn to use hpack.  
(i understand the difficulty to pass the information to it - probably a rudimentary `stack.yaml` with just the resolver info would do.)
For now, I will stay with old cabal - unhappily.

**Comment by sol** [comment]
I think this is really a `stack` question.  `hpack` is independent from `stack` and can be used separately.
