### ISSUE TITLE
Generating a *.cabal file doesn't preserve newlines in field values

### ISSUE THREAD

**Issue by greatBigDot** [sol/hpack#361]
I often have a multi-paragraph `description` field when setting up packages, so my `package.yaml` looks something like this:

    description: >-
      paragraph1

      paragraph2

(This uses the "folded style" of embedding newlines in YAML fields (there are [very many ways](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210) to do this).)

Unfortunately, the generated `*.cabal` file does not include newlines:

    description: paragraph1
                 paragraph2

Cabal has a unique syntax for newlines; currently you must make a line containing nothing but an indented period (`.`) to signify a blank line, according to [the documentation](https://www.haskell.org/cabal/users-guide/developing-packages.html#package-descriptions).

    description: paragraph1
                 .
                 paragraph2

Apparently [this is being phased out](https://github.com/haskell/cabal/issues/5971), at which point I suppose a blank line will do. But currently hpack does neither, instead removing the blank lines and replacing them with single line breaks.

**Comment by dcastro** [comment]
Just had this issue (also asked in #130), the answer is to use one of the many YAML block indicators: `>`, `>+`, `>-`, `|`, `|+`, `|-`. The ones beginning with `|` preserve newlines.

Useful guide: https://yaml-multiline.info

**Comment by sol** [comment]
@greatBigDot I think the following will work for your use case:
```
description: |
  paragraph1

  paragraph2
```

**Comment by sol** [comment]
Hpack accepts empty lines in `description` and will insert `.` as needed.

The issue at hand boils down to using appropriate YAML syntax (@dcastro for chiming in).

Note that you can always double-check your YAML syntax by converting to JSON (e.g. use `yaml2json`).

Or, if you dislike YAML, you can always write your `package.yaml` in JSON altogether.

If anybody things we can improve the docs somehow, then please open a PR.

Closing.

**Comment by sol** [comment]
@chrissound can you try using `>-` instead of `|`?

**Comment by chrissound** [comment]
That instead gives me an error of `package.yaml:2:13: did not find expected comment or line break while scanning a block scalar` when running `hpack`.
