### ISSUE TITLE
The field ordering in generated cabal files is not consistent.

### ISSUE THREAD

**Issue by Javran** [sol/hpack#364]
@fergushenderson found out that field ordering are not consistent: an example can be seen from [string-conversions](https://github.com/soenkehahn/string-conversions/blob/master/string-conversions.cabal). In particular `default-language` is before `build-depends` in `library`, but after `build-depends` in `test-suite spec`.

**Comment by sol** [comment]
This is by design, `hpack` tries to produce `.cabal` files with minimal diffs.  If you delete any existing `.cabal` file before running `hpack` you will get deterministic fields orders.
