### ISSUE TITLE
Cabal parser error when trying to use reexported-modules feature

### ISSUE THREAD

**Issue by afcowie** [sol/hpack#367]
Poking around in the https://github.com/well-typed/optics project, I saw they had a batteries-included  **optics** package in addition to the more limited actual  **optics-core**, etc packages. Having tried (and failed) to build something like that in the past for one of my own projects, I was astonished to see a new _.cabal_ field in their repo, `reexported-modules`, <https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-library-reexported-modules>. 

Sure enough, **hpack** has `reexported-modules` listed in the README, but when I tried giving that field a list of module names:

```
  reexported-modules:
      - Thingy.One
      - Thingy.Two
      - Thingy.Three
```

I got a parser error back from Cabal:

```
Unable to parse cabal file from package /home/andrew/src/haskell/blah/thingy.cabal

- 62:7: 
unexpected 'T'
expecting space, comma, white space or end of input

Thingy.One
Thingy.Two
Thingy.Thre
```

it looks like Cabal wants a comma separated list there, but hpack is generating a bare list of module names. That something you want to know about?

AfC

**Comment by sol** [comment]
Hey!  Thanks for reporting this!

This should be fixed in 0.32.0.
