### ISSUE TITLE
don't list Setup.hs as a module

### ISSUE THREAD

**Issue by simonmichael** [sol/hpack#37]
Just trying out this tool.. loving it so far!

With source-dirs: . , Setup.hs is included in exposed-modules which is undesirable.

**Comment by sol** [comment]
Nice catch!  I guess we want to special case the situation when inferring modules for `.`.

A patch would be welcome, but I'll also try to free up some time to look into it later.

**Comment by soenkehahn** [comment]
Fixed on hackage as `0.5.3`. Closing.

**Comment by simonmichael** [comment]
Thanks!
