### ISSUE TITLE
data-dir recurse

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [sol/hpack#377]
It seems like it would be helpful if data-dir or something similar would recurse into the specified directory and add all the files found to data-files.

Is this something you would consider?

**Comment by sol** [comment]
@BebeSparkelSparkel sorry for the late response.  `data-files` accepts glob patterns, e.g. `data-files: data/**/*.js`.  Can you try if this solves your use case?

**Comment by BebeSparkelSparkel** [comment]
@sol Thanks for the response. I could try but I don't remember what I was using this for. If I do, I'll let you know.
