### ISSUE TITLE
easier multi-line description formatting

### ISSUE THREAD

**Issue by simonmichael** [sol/hpack#38]
I'd like to write a multi-line description in the yaml file, with long lines broken for readability. Ideally the line breaks would be preserved in the cabal file, for the same reason. In the yaml file I tried `description:` (complains if the text contains :), `description: >` and `description: |`. The last seemed to work best, but I think it is adding cabal's `.` lines for every line break; I think it should add these only for blank lines (paragraph separators).

I don't know if it's possible to preserve line breaks all the way through to the cabalish-haddock rendering on hackage - probably that's not desirable.

**Comment by simonmichael** [comment]
PS to simulate how it would look on hackage, I put the generated cabal description in a haddock comment, with indent removed and `.` lines replaced by blank lines. Here's the text I was using:
```
description : |
  A simple hakyll website builder suitable for (eg) software-related websites, intended to be used as-is without recompilation. Features:

  - renders markdown and common web file types found in standard places
  - a site.tmpl template will be used when rendering markdown files
  - "- toc" in markdown files is replaced by a table of contents
  - fenced code blocks are appropriately syntax-highlighted by highlighting-kate
    (you should provide a syntax.css)

  See the module doc (homepage link) for precise details.

```

**Comment by sol** [comment]
I think | should do what you want since be1f199.  Can you verify that you use the latest version?

**Comment by simonmichael** [comment]
Perfect! I'm now using the latest release. stack installed 0.4.0 for some reason, sorry about that.
