### ISSUE TITLE
hpack does not use spdx style license string when using verbatim cabal version > 2.4

### ISSUE THREAD

**Issue by expipiplus1** [sol/hpack#383]
With `verbatim: cabal-version: 3.0` hpack still puts `BSD3` as the license field in the cabal file which cabal-3 chokes on

**Comment by dschrempf** [comment]
In this case, I do not think this is a bug in `hpack`. One has to specify an SPDX conform license identifier. See https://spdx.org/licenses/.

**Comment by expipiplus1** [comment]
Sorry, I should have mentioned that this is with the automatic licence type detection.

**Comment by sol** [comment]
Hpack does not change its behavior on any `verbatim` fields.

Going forward, what we can do is make sure that `hpack` infers the correct `cabal-version` for your use case and renders the license correctly.

To do so, please provide a minimal example that reproduces your issue.  That will help a lot! Thanks!

**Comment by expipiplus1** [comment]
Ah, that makes sense.

My use case was the `visibility: public` thing, which I think #385 solves for me.
