### ISSUE TITLE
Mixed up github username and reponame

### ISSUE THREAD

**Issue by vorotynsky** [sol/hpack#393]
Hello, after update hpack miss GitHub URL and generates `https://github.com/reponame/username`.

| Property     | Version    |
| -----------: | :--------- |
| OS           | Arch linux |
| Stack        | 2.3.1      |
| hpack        | 0.34.0     |

---
My example.

Stack file
```
name:                HLasm
version:             0.1.0.0
github:              "vorotynsky/HLasm"
```

Generated cabal file
```
homepage:       https://github.com/HLasm/vorotynsky#readme
bug-reports:    https://github.com/HLasm/vorotynsky/issues

--- ... ---

source-repository head
  type: git
  location: https://github.com/HLasm/vorotynsky
```

**Comment by sol** [comment]
Thank you for reporting this.  How did you install `hpack-0.34.0`?

`cabal-install` should not install that version.

**Comment by vorotynsky** [comment]
I did update via pacman (arch package manager)

**Comment by vorotynsky** [comment]
Oh, I found, that you [fix it](https://github.com/sol/hpack/releases/tag/0.34.1).

**Comment by sol** [comment]
`pacman` should not pull / install deprecated packages.  You may want to report this as a bug against `pacman`.

**Comment by sol** [comment]
@felixonmars `hpack-0.34.0` has be released 2020-05-14 15:19:02 UTC and been deprecated shortly after.

From what I understand from https://www.archlinux.org/packages/community/x86_64/haskell-hpack/, it has packaged for Arch on 2020-05-22 14:13 UTC, that is 8 days after it has been deprecated.  I'm not sure what options there are in Arch to deprecate a package, but can you help take appropriate actions?

**Comment by sol** [comment]
@felixonmars it may make sense to ensure that Arch does not package deprecated packages in the future.

**Comment by sol** [comment]
@felixonmars https://hackage.haskell.org/packages/preferred-versions <- this is what you should take into account when packaging versions.

A copy of that file should also be include in the index tar ball.

I'm somewhat surprised that this is not taken into account already.  How do you guys ensure that you don't package, e.g. `stack-9.9.9`?

**Comment by felixonmars** [comment]
@sol The version checking tool I use - nvchecker already took this into account so the deprecated highest version should be avoided already. Since there is no automation other than that, I somehow overlooked that on the previous version myself.

Working on a rebuild now, sorry for the confusion!
