### ISSUE TITLE
Library in root directory is not found

### ISSUE THREAD

**Issue by andrewufrank** [sol/hpack#398]
I have a perhaps unusual set up as my `Lib` directory is in the root of the project folder (not under, say, `src`): 
 The structure of the project directory is 

````
| 
|- src (with the main.hs) 
|- Lib With files modules Lib.A in file A.hs, Lib.B in file B.hs ...
````

in package.yaml I have
````
library:
  source-dirs: .
  exposed-modules: Lib 
````
but get the error
````
Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3: can't find source for Lib in ./.,
````
What is to be put into the source-dirs to find the Lib directory in the project root?  I assume this is either a bug in hpack or in cabal: I guess the `./.` in the entry confuses cabal and is perhaps not a legal path expression. The produced cabal file lookes like:

````
library
  exposed-modules:
      Lib
  other-modules:
      Bake
      Lib.CmdLineArgs
      ...
      Paths_ssg
  hs-source-dirs:
      ./.
  ghc-options: -Wall
  build-depends:
      base
    , containers
````

**Comment by andrewufrank** [comment]
I guess I misunderstood that the exposed-modules field would accept a directory (and include all what is under it) - which would be useful. 
I have the impression that some slides from the presentation was giving me the impression (and perhaps some test case I ran produced this effect). 
Please produce some decent documentation; a tool must be useable for a newbie otherwise your community never grows; and then it has to run immediately and produce decent error messages. I would love to see some decent follower from cabal - which was a very good idea in its time (I use it likely since 1995?) but improvement is possible and required.

**Comment by sol** [comment]
@andrewufrank hey! I'm glad you figured it out yourself.  If you have any specific input on how to improve the docs, please let me know.
