### ISSUE TITLE
Incorrect cabal-version is generated

### ISSUE THREAD

**Issue by gromakovsky** [sol/hpack#400]
My `package.yaml` is very small:
```
name:                indigo

library:
  source-dirs: src
  generated-other-modules:
    - Paths_indigo

  default-extensions: [ RebindableSyntax, OverloadedStrings]
```

It produces the following `indigo.cabal` file:
```
cabal-version: 2.0

-- This file has been generated from package.yaml by hpack version 0.34.2.
--
-- see: https://github.com/sol/hpack

name:           indigo
version:        0.0.0
build-type:     Simple

library
  exposed-modules:
      Indigo
  other-modules:
      Paths_indigo
  autogen-modules:
      Paths_indigo
  hs-source-dirs:
      src
  default-extensions: RebindableSyntax OverloadedStrings
  default-language: Haskell2010
```

When I run `cabal build` I get this:
```
cabal: The package uses RebindableSyntax with OverloadedStrings or
OverloadedLists in default-extensions, and also Paths_ autogen module. That
configuration is known to cause compile failures with Cabal < 2.2. To use
these default-extensions with Paths_ autogen module specify at least
'cabal-version: 2.2'.
```

So I suppose `hpack` should set `cabal-version` to 2.2 in this case. As a workaround I do
```
verbatim:
  cabal-version: 2.2
```
but it would be nicer if it was handled by `hpack` itself.

**Comment by sol** [comment]
@gromakovsky hey! Thanks for reporting this.  https://github.com/sol/hpack/pull/405 is my attempt to address this.  Please let me know if you have any feedback.

**Comment by gromakovsky** [comment]
#405 is closed and doesn't have any commits as of now. AFAIU the fix is in https://github.com/sol/hpack/commit/bd27333d7a3c52b14674e51ae13e140e25e7682a. I'll test it when a new release reaches me or maybe will test manually with master. This issue is closed anyway, so there should be no rush. Thanks for the fix!
