### ISSUE TITLE
Tracking issue for failure to run when installed from ubuntu repos

### ISSUE THREAD

**Issue by expipiplus1** [sol/hpack#401]
https://bugs.launchpad.net/ubuntu/+source/haskell-hpack/+bug/1902081

**Comment by expipiplus1** [comment]
lotuspsychje on freenode suggests marking this as "affects me too"

**Comment by sol** [comment]
@expipiplus1 hey! Thanks for bringing this up!

Is there anything we can do in `hpack` to help resolve the broken Ubuntu build?

If not, I would tend to close this issue here.  In general, I try to keep open issues "actionable".

**Comment by expipiplus1** [comment]
No idea sorry, I don't even use Ubuntu! Just happened to stumble on this in a GitHub actions runner.
