### ISSUE TITLE
How can I use hpack to generate common imports?

### ISSUE THREAD

**Issue by philderbeast** [sol/hpack#486]
There is this disclaimer about the use of verbatim from the readme.

"Disclaimer: The content of verbatim fields are merged into the generated .cabal file as a final step, after Hpack is done with most of its work. Before that final step Hpack does not look at any verbatim fields. Consequently, the content of a verbatim field does not affect any other fields that are populated by Hpack. As an example, if you use verbatim to override hs-source-dirs, the overridden information will not be used when Hpack infers exposed-modules or other-modules."

Because verbatim fields are added last we can't use them to generate common imports because cabal expects those fields before other fields.

```rst
-  ``import`` must be the first field in a section. Since Cabal 3.0 imports
   are also allowed inside conditionals.
```

SOURCE : [`doc/cabal-package.rst`](https://github.com/haskell/cabal/blame/9f584153bf3886eaace65e9ab87d18c5d77d7b45/doc/cabal-package.rst#L2763-L2764)

As for cabal, must import really be the first field in a section, https://github.com/haskell/cabal/issues/8067?

How can I use hpack to generate common imports if an import must be the first field in a section?

**Comment by sol** [comment]
If you can, use Hpack's and YAML features instead of Cabal's common sections.  Take a loot at

- https://github.com/sol/hpack#defaults (Hpack's `default` machinery)
- https://github.com/sol/hpack#not-repeating-yourself (YAML anchors)

**Comment by sol** [comment]
@philderbeast one advantage of using Hpack's features is that your `.cabal` files will work with older versions of `cabal` (at the cost of bigger `.cabal` files).

**Comment by philderbeast** [comment]
@sol hpack is inspiring!

I'm trying to reproduce a `.cabal` file, one that uses `common` and `import` and that doesn't seem possible.

**Comment by sol** [comment]
On Hackage as `hpack-0.34.7`.

**Comment by philderbeast** [comment]
Thanks @sol. I ran a quick test and the sorting works save for related problems #492 and #493.
