### ISSUE TITLE
Support for "build-type: Custom"

### ISSUE THREAD

**Issue by peti** [sol/hpack#49]
Is it possible to specify `build-type: Custom` somehow? I tried adding an appropriate entry to my `package.yaml` file, but `hpack` complained about an unsupported entry.

**Comment by mitchellwrosen** [comment]
`build-type: Simple` is hard-coded

**Comment by sol** [comment]
There is no support for `build-type: Custom` and it's unlikely to happen.  This feature would tie `hpack` to `Cabal` and would make it hard to implement alternative consumers of `package.yaml` files.

**Comment by peti** [comment]
The problem I have is that it's not possible to run a `doctest` test suite reliably in a "Simple" build: https://github.com/fpco/stackage/issues/1616. Or, well, it is possible but it requires manual maintenance of a list of dependencies, which isn't exactly pleasant.

**Comment by sol** [comment]
After discussing this again with @soenkehahn I'm willing to compromise on my original goal for the sake of making `hpack` as useful as possible.

To that end I am willing to accept a patch for `build-type`.

PRs please!

**Comment by sol** [comment]
This is released by now.
