### ISSUE TITLE
Two cabal-version fields with verbatim.

### ISSUE THREAD

**Issue by philderbeast** [sol/hpack#493]
If I'm using a verbatim block at the top level for more than just `cabal-version` then I end up with two such `cabal-version` fields when hpack renders the cabal file and `cabal build` fails to build the package.

```
> cabal build
The field "cabal-version" is specified more than once at positions _ _
```

See #494 for the reproduction.

**Comment by sol** [comment]
@philderbeast I think the issue is that you provided `cabal-version: ..` within a string literal.  That way `hpack` has no basis to understand that it is a key/value pair.  Try this instead:

```yaml
verbatim:
  - cabal-version: 3.0
  - |
    common settings
      foo
      bar
      baz
```

**Comment by philderbeast** [comment]
Thanks @sol. This is one instance where hpack-dhall cannot represent that mix of list elements.

```
-- package.dhall snippet

        , verbatim =
          [ { cabal-version = "3.0" }
          , ''
            common settings
              foo
              bar
              baz
            ''
          ]

> dhall-hpack-cabal

Error: List elements should all have the same type

- { … : … } (a record type)
+ Text
```

**Comment by sol** [comment]
I can't help with Dhall, but conceptually you want a sum type here if Dhall supports that.

**Comment by sol** [comment]
If you are already using Dhall, it might make sense to use Dhall features to DRY up your package config instead of relying on `verbatim` and cabal common sections.

`verbatim` is really just meant as a last resort escape hatch.
