### ISSUE TITLE
Support for "build-tools:" stanza

### ISSUE THREAD

**Issue by peti** [sol/hpack#50]
It seems impossible to specify a build tool with hpack. Am I missing something?

**Comment by sol** [comment]
This one is not implemented yet.

**Comment by sol** [comment]
As cabal's support for `build-tools` is not that great, this didn't make it to the top of my list of priorities.  But if somebody opens a PR it has good chances to go on `master`.  Only requirement is:

 * use TDD during development

**Comment by mgsloan** [comment]
Stack does support `build-tools`.  This would be a welcome addition.
