### ISSUE TITLE
Binaries & releases

### ISSUE THREAD

**Issue by dcastro** [sol/hpack#514]
I'm setting up a new CI and trying to use hpack.
I noticed 2 problems:

1. The readme says we should use the script at `https://github.com/sol/hpack/raw/master/get-hpack.sh` to get the latest binaries, but that link is broken. It should be updated to `https://raw.githubusercontent.com/sol/hpack/main/get-hpack.sh`

2. That script installs a pretty old version of hpack, version 0.34.2. That seems to be due to the fact there have been no [binary releases](https://github.com/sol/hpack/releases) since 0.34.2; in other words, we're missing the binaries for these versions: 0.34.3, 0.34.4, 0.34.5, 0.34.6, 0.34.7, 0.35.0

**Comment by sol** [comment]
https://github.com/sol/hpack/pull/590

**Comment by sol** [comment]
https://github.com/sol/hpack/pull/591
