### ISSUE TITLE
Release 0.35.0 is missing on github

### ISSUE THREAD

**Issue by andys8** [sol/hpack#534]
hpack is currently at v0.35.0

https://github.com/sol/hpack/blob/7ec449e138c1fe96a659291c442f0aea6a80cf5b/package.yaml#L2

https://hackage.haskell.org/package/hpack-0.35.0

## Issue

But the latest release on github is `0.34.2`

https://github.com/sol/hpack/releases/tag/0.34.2

https://github.com/sol/hpack/releases

**Comment by sol** [comment]
@andys8 we have a tag for 0.35.0.  What exactly were you looking for? Binary releases?

**Comment by andys8** [comment]
Yes, there is no release entry and there are no assets. GitHub releases seems to be used by this script.

https://github.com/sol/hpack/blob/7ec449e138c1fe96a659291c442f0aea6a80cf5b/get-hpack.sh#L11

![Screenshot_2022-12-03-03-22-59-02_4d38fce200f96aeac5e860e739312e76~2](https://user-images.githubusercontent.com/13085980/205418086-ae7b6ae4-7729-4dc9-b84d-1e5531f3cea9.jpg)

**Comment by sol** [comment]
We did have a travis action for releasing Linux and OSX binaries, but as of now we don't have a GitHub action for binary releases.  I'm not sure if and if yes when I'll have time to look into this.

Do you have an immediate need for this?

**Comment by andys8** [comment]
> Do you have an immediate need for this?

Nope, all good
