### ISSUE TITLE
No asm-sources field?

### ISSUE THREAD

**Issue by lierdakil** [sol/hpack#573]
Running into a bit of an issue, newer `stack` refuses to compile asm sources listed in `c-sources` and hpack doesn't have [`asm-sources`](https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-asm-sources). Suggestions?

**Comment by lierdakil** [comment]
Okay, after some fumbling about, liberal use of `verbatim` kinda works.

Cabal since 3.10 or something doesn't allow assembly files in `c-sources`, and stack follows that. So the lack of `asm-sources` field is quite annoying when you want to bundle some assembly.

**Comment by sol** [comment]
This should be an easy addition. And yes, please use `verbatim` for the time being.
