### ISSUE TITLE
Support reexported-modules

### ISSUE THREAD

**Issue by phadej** [sol/hpack#59]
That would require setting `cabal-version:  >= 1.21`

**Comment by sol** [comment]
@phadej Hey, sorry for the late reply.  Yes, I think this is a nice feature.  I would accept a patch for it.  The following points are important to me:

- only set `cabal-version: >= 1.21` if re-exported modules are used
- use TDD during development

**Comment by sol** [comment]
Done by @mitchellwrosen.
