### ISSUE TITLE
Default `description` to `synopsis`

### ISSUE THREAD

**Issue by sol** [sol/hpack#6]
Hackage requires a `description` for every package.  If `description` is not specified, we could fallback to `synopsis`.

**Comment by peti** [comment]
:+1:

**Comment by mitchellwrosen** [comment]
Hackage apparently no longer requires a `description`

**Comment by tfausak** [comment]
Unfortunately cabal-install still warns as of version 1.24.0.0.

**Comment by sol** [comment]
If Hackage no longer requires that, then I would skip this for now and hope that cabal gets fixed.

From my perspective it is a valid decision not to add a description and I don't want to make it unnecessarily complicated with `hpack`.

**Comment by sol** [comment]
Please raise your voice if you have a different opinion, otherwise I will close this ticket and the corresponding pull request.
