### ISSUE TITLE
Specification of multiple packages?

### ISSUE THREAD

**Issue by mgsloan** [sol/hpack#62]
Perhaps it makes sense to be able to specify multiple packages in one hpack file?  Then, common dependencies and flags can be factored out. 

The only downside I can see to this is that it makes it easier to inadvertently add unused dependencies.  Ideally, these'd be detected (https://github.com/commercialhaskell/stack/issues/39)

So, this'd mean you'd potentially end up with a `packages.yaml` next to your `stack.yaml.  Alternatively, I could even imagine stack supporting inline hpack in its packages list (related to https://github.com/sol/hpack/issues/61).  Not sure the complexity is worth it, or whether it'd be a positive effect on stack.yaml - just a thought!

**Comment by sol** [comment]
I'm open to this idea, as long as it is not tied to `stack` exclusively.  @mgsloan if you want to work on this, please feel free to lay out the details.

If adding inline hpack to `stack` requires changes to `hpack` itself, I'm also happy to accept patches for that.

**Comment by mgsloan** [comment]
Yup, it certainly wouldn't look like an exclusive integration.  The main tricky part of the integration is trying to minimize the frequency of running hpack / writing new cabal files (by paying attention to file modification times, etc).

I don't have time right now, but if someone does want to add this to stack, I'd be keen on the idea.

**Comment by liskin** [comment]
hpack now supports file inclusion (https://github.com/sol/hpack/commit/d99bf2ffd4f416804d27dd5c417478dac45ffcfe#diff-04c6e90faac2675aa89e2176) and yaml itself supports factoring out common parts (https://github.com/sol/hpack/commit/309d9f4b8ba295034820cb4d852eaebc013b1175). Is this a sufficient solution to your usecase @mgsloan?

**Comment by mgsloan** [comment]
Yep, I think that should be sufficient.  Good stuff!
