### ISSUE TITLE
Automatic generation of hpack from .cabal files?

### ISSUE THREAD

**Issue by mgsloan** [sol/hpack#63]
Hpack looks really nice, great work!  I think a good step towards adoption would be to support automatic conversion of cabal files to hpack format.  This could be done in a new package, `hpack-convert`, or something, to avoid a dependency on Cabal in the main hpack library (maybe that dependency would be ok, though?).

**Comment by soenkehahn** [comment]
Yes, this is definitely something we thought about before. I would prefer this to be in the same project, mainly because I want the `hspec` executable to be able to perform the conversion.

**Comment by sol** [comment]
Yes, this is a frequently requested feature and would be an awesome addition to `hpack`.  In general I would prefer a separate package.

@soenkehahn Would you imagine that calling `hpack` in a situation where (a) there is no `package.yaml` and (b) there is a cabal file, `hpack` would generate a `package.yaml`?  In that case we would only need one `hpack` command, that does not require any arguments.

**Comment by mgsloan** [comment]
Hmm, switching behaviors based on context like that seems unpredictable, I think I'd prefer a special command or flag.

I don't see this as really being that difficult.  The main bits that could use some fanciness is the error messages for cases that hpack can't handle, and extracting out the common duplication among sections.

**Comment by soenkehahn** [comment]
@sol: I agree with @mgsloan: I would prefer that `hpack` has to be explicitly asked (through a flag) to create a `package.yaml`. I remember calling `hpack` by mistake on projects that don't have a `package.yaml`. I imagine it would be a bit inconvenient if `hpack` would just create one in that case.

**Comment by yamadapc** [comment]
I started working on this. Need to clean-up the yaml generation bit a lot and I think I broke something, but from hpack.cabal it's generating:

https://gist.github.com/49b34220077bdd9e16ef6d0126d1d66a

**Comment by mgsloan** [comment]
Good work @yamadapc !!
