### ISSUE TITLE
Use `path` and `path-io`

### ISSUE THREAD

**Issue by phadej** [sol/hpack#67]
That would make codebase a bit more robust.

**Comment by mitchellwrosen** [comment]
There aren't many file paths in the `hpack` codebase - basically, just the directory to run in, `package.yaml`, and `<name>.cabal`. I don't know if it's worth bringing in the dependency.

**Comment by sol** [comment]
Yes, same thought here. Low priority for me.

**Comment by phadej** [comment]
I could do this myself, IMHO it's worth the dependency. As it's good creating a `newtype` for the filepaths, and DIY is more trouble than done and tested packages out there.

**Comment by sol** [comment]
@phadej would you still be interested to open a pull request for this? I would like to have it for #119.

**Comment by phadej** [comment]
I could take a look next week
