### ISSUE TITLE
Allow specifying license file

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#73]
My license files typically have an extension. hpack only looks for a file called `LICENSE` with no extension. I tried to manually set the `license-file`, but that is an unknown field. I would like to be able to manually set the license file. It would be nice if license files with extensions could automatically be found.

**Comment by mitchellwrosen** [comment]
I implemented this in #74 but I didn't include any automatic discovery.

**Comment by tfausak** [comment]
Fixed by #74. Thanks!
