### ISSUE TITLE
Source repositories other than github

### ISSUE THREAD

**Issue by wiz** [sol/hpack#79]
At least gitlab and bitbucket shortcuts are needed, together with a mirror of `source-repository` stanza with type-location-... fields.

**Comment by sol** [comment]
Hey @wiz, so far I added new functionality to `hpack` as I needed it.  For source repositories, what exactly do you want to use right now?  Just arbitrary Git repos, e.g.

```yaml
git: https://gitlab.com/gitlab-org/gitlab-ce.git
```

or something else?

**Comment by wiz** [comment]
That would be a good start for sure. I'm not entirely sold on service-specific "shortcuts", but they can be helpful (e.g. adding "issues" section).

**Comment by mgsloan** [comment]
There are two reasons I think it makes sense to have a github shortcut:

1) Its sheer popularity.  We can cover something like 80-90% of repos with that one shortcut, but based on my rough estimates of usage within the haskell community, adding other host shortcuts would only trim a percent here and there.

2) The existence of the [hub](https://github.com/github/hub) tool, which makes git able to handle repository URLs like `sol/hpack` - the exact same syntax as the shortcut. It also allows cool stuff like `git checkout PR_URL`.

**Comment by sol** [comment]
@mgsloan I second that!  Thanks for chiming in!
