### ISSUE TITLE
Ordered input on tests, flags executables etc.

### ISSUE THREAD

**Issue by phadej** [sol/hpack#84]
Can we change

```hs
Maybe (HashMap String (CaptureUnknownFields (Section ExecutableSection)))
```
to
```
Maybe (Map String (CaptureUnknownFields (Section ExecutableSection)))
```

or alternatively traverse them in name order. Time from time ordering of multiple tests changes. I guess I'm unlucky, I got a hashclash.

**Comment by sol** [comment]
Yes, using a Map sounds good to me.  Can you open a PR?

**Comment by sol** [comment]
see #85
