### ISSUE TITLE
Support npm-style version ranges?

### ISSUE THREAD

**Issue by tfausak** [sol/hpack#91]
I would love to be able to specify version numbers using npm's [advanced range syntax](https://docs.npmjs.com/misc/semver#advanced-range-syntax). Stuff like `1.2.x`, `~1.2.3`, and `^1.2.3`. I think the [semver-range](http://hackage.haskell.org/package/semver-range-0.1.1/docs/Data-SemVer.html) package can represent them, but I haven't ever played with it.

**Comment by soenkehahn** [comment]
Btw, `cabal` (and `hpack`) already support e.g. `1.2.*`. Which I guess is equal to `1.2.x`.

**Comment by tfausak** [comment]
That's true. I'm more interested in the tilde and caret specifiers.

**Comment by mitchellwrosen** [comment]
I'm willing to implement this but I want to make sure it's a welcome change. What do you think, @sol?

**Comment by sol** [comment]
Skimming through the documentation, I don't think you can translate this to Haskell directly. It seems that Node always uses major, minor, patch. This is not true for the Haskell. Firstly the pvp defines the major version as `x.y`, secondly you see a mixture of versions like `2`, `2.1`, `2.1.1`, `2.0.0.1` on Hackage.

So if somebody thinks it's worth working on this, the first step would probably be to write down how exactly we would translate this to Haskell.

It may also make sense to consider each feature individually. E.g. I think version ranges could be nice, if we can figure out the semantics. On the other hand I'm not excited about `.x` as we already have star syntax.

**Comment by mitchellwrosen** [comment]
Hackage does allow e.g. `2`, but to the cabal solver, this is the same as `2.0.0.0`, no?

I think the overall ideas do translate directly to Haskell, we'd just have to account for major versions taking up two slots rather than one.

Agreed that `.x` doesn't make much sense, and it would be best to start with just one, like `1.0 - 2.0`

**Comment by soenkehahn** [comment]
IIRC to `cabal` `2` is not the same as `2.0.0.0`. I think the constraint `<= 2` would even disallow `2.0.0.0` because `Data.Version` says that `2 < 2.0.0.0`. I may be wrong, though.

**Comment by sol** [comment]
I have some similar resemblance of something fishy there

**Comment by sol** [comment]
As much as I like this idea, I think it's not straight forward to apply this to Cabal (see the comments of @soenkehahn an me above).

If somebody still wants aspects of this to happen (e.g. version ranges), then please feel free to open individual tickets for that.
